#TARGET_ARCH = linux
TARGET_ARCH = linux64

CC     = g++
OPT    = -O3
DEBUG  = -g
OTHER  = -Wall -Wno-deprecated
# CFLAGS = $(OPT) $(OTHER)
CFLAGS = $(DEBUG) $(OTHER)

MODULE = run
SRCS = pi_cpu.cpp
#SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs
