<< RDATA1_SR_S2 
                    << RDATA2_SR_S2 
                    << DEST_RE_S2 
                    << EXE_RES_RE_S1
                    << DEST_RM_S2 
                    << MEM_RES_RM_S1 
                    << RADR1_SD_S2 
                    << EXE_DEST_RD_S2
                    << RADR2_SD_S2 
                    << EXE2MEM_EMPTY_SE_S2 
                    << MULT_INST_RE_S2 
                    << MULT_INST_RM_S2
                    << DEC2EXE_EMPTY_SD_S2 
                    << MEM_LOAD_RE_S2 
                    << BP_MEM2WBK_EMPTY_SM_S2